# Built by vsrupeshkumar
services:
  - type: web
    name: kubryx-cipher
    env: node
    region: oregon
    plan: free
    rootDir: ciphervault/CipherVault-main
    buildCommand: npm install --include=dev && npm run build
    startCommand: node index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: PORT
        value: "3004"
      - key: SOLANA_RPC_URL
        value: https://api.devnet.solana.com
